"""Initial schema with API Key terminology

Revision ID: 0c84d79e5030
Revises: 
Create Date: 2026-01-30 08:44:13.114458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0c84d79e5030'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key_usage_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action', sa.Enum('SHARED', 'CONSUMED', 'GENERATED', 'REVOKED', 'SWITCHED', name='apikeyaction'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_key_usage_history_action'), 'api_key_usage_history', ['action'], unique=False)
    op.create_index(op.f('ix_api_key_usage_history_api_key_id'), 'api_key_usage_history', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_api_key_usage_history_timestamp'), 'api_key_usage_history', ['timestamp'], unique=False)
    op.create_index(op.f('ix_api_key_usage_history_user_id'), 'api_key_usage_history', ['user_id'], unique=False)
    op.create_table('shared_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('BIGMODEL', 'ZAI', name='apikeyprovider'), nullable=False),
    sa.Column('encrypted_api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'REVOKED', name='apikeystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('total_uses', sa.Integer(), nullable=False),
    sa.Column('api_key_metadata', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('litellm_model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_provider_unique', 'shared_api_keys', ['user_id', 'provider'], unique=True)
    op.create_index(op.f('ix_shared_api_keys_provider'), 'shared_api_keys', ['provider'], unique=False)
    op.create_index(op.f('ix_shared_api_keys_status'), 'shared_api_keys', ['status'], unique=False)
    op.create_index(op.f('ix_shared_api_keys_user_id'), 'shared_api_keys', ['user_id'], unique=False)
    op.create_table('unified_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', name='unifiedapikeystatus'), nullable=False),
    sa.Column('api_key_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('litellm_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    op.create_index('idx_user_status', 'unified_api_keys', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_unified_api_keys_user_id'), 'unified_api_keys', ['user_id'], unique=False)
    op.drop_index('ix_person_age', table_name='person')
    op.drop_index('ix_person_gender', table_name='person')
    op.drop_index('ix_person_name', table_name='person')
    op.drop_table('person')
    op.drop_index('ix_town_name', table_name='town')
    op.drop_index('ix_town_population', table_name='town')
    op.drop_table('town')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('town',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('population', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('town_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='town_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_town_population', 'town', ['population'], unique=False)
    op.create_index('ix_town_name', 'town', ['name'], unique=True)
    op.create_table('person',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('town_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['town_id'], ['town.id'], name='person_town_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='person_pkey')
    )
    op.create_index('ix_person_name', 'person', ['name'], unique=True)
    op.create_index('ix_person_gender', 'person', ['gender'], unique=False)
    op.create_index('ix_person_age', 'person', ['age'], unique=False)
    op.drop_index(op.f('ix_unified_api_keys_user_id'), table_name='unified_api_keys')
    op.drop_index('idx_user_status', table_name='unified_api_keys')
    op.drop_table('unified_api_keys')
    op.drop_index(op.f('ix_shared_api_keys_user_id'), table_name='shared_api_keys')
    op.drop_index(op.f('ix_shared_api_keys_status'), table_name='shared_api_keys')
    op.drop_index(op.f('ix_shared_api_keys_provider'), table_name='shared_api_keys')
    op.drop_index('idx_user_provider_unique', table_name='shared_api_keys')
    op.drop_table('shared_api_keys')
    op.drop_index(op.f('ix_api_key_usage_history_user_id'), table_name='api_key_usage_history')
    op.drop_index(op.f('ix_api_key_usage_history_timestamp'), table_name='api_key_usage_history')
    op.drop_index(op.f('ix_api_key_usage_history_api_key_id'), table_name='api_key_usage_history')
    op.drop_index(op.f('ix_api_key_usage_history_action'), table_name='api_key_usage_history')
    op.drop_table('api_key_usage_history')
    # ### end Alembic commands ###
