"""add litellm_user_id to users

Revision ID: 9ea5b0492874
Revises: 
Create Date: 2026-01-30 10:53:30.743847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9ea5b0492874'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('litellm_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('shared_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.Enum('BIGMODEL', 'ZAI', name='tokenvendor'), nullable=False),
    sa.Column('encrypted_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'REVOKED', name='tokenstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('total_uses', sa.Integer(), nullable=False),
    sa.Column('token_metadata', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_vendor_unique', 'shared_tokens', ['user_id', 'vendor'], unique=True)
    op.create_index(op.f('ix_shared_tokens_status'), 'shared_tokens', ['status'], unique=False)
    op.create_index(op.f('ix_shared_tokens_user_id'), 'shared_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_shared_tokens_vendor'), 'shared_tokens', ['vendor'], unique=False)
    op.create_table('token_usage_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action', sa.Enum('SHARED', 'CONSUMED', 'GENERATED', 'REVOKED', 'SWITCHED', name='tokenaction'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_usage_history_action'), 'token_usage_history', ['action'], unique=False)
    op.create_index(op.f('ix_token_usage_history_timestamp'), 'token_usage_history', ['timestamp'], unique=False)
    op.create_index(op.f('ix_token_usage_history_token_id'), 'token_usage_history', ['token_id'], unique=False)
    op.create_index(op.f('ix_token_usage_history_user_id'), 'token_usage_history', ['user_id'], unique=False)
    op.create_table('unified_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', name='unifiedtokenstatus'), nullable=False),
    sa.Column('token_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('idx_user_status', 'unified_tokens', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_unified_tokens_user_id'), 'unified_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unified_tokens_user_id'), table_name='unified_tokens')
    op.drop_index('idx_user_status', table_name='unified_tokens')
    op.drop_table('unified_tokens')
    op.drop_index(op.f('ix_token_usage_history_user_id'), table_name='token_usage_history')
    op.drop_index(op.f('ix_token_usage_history_token_id'), table_name='token_usage_history')
    op.drop_index(op.f('ix_token_usage_history_timestamp'), table_name='token_usage_history')
    op.drop_index(op.f('ix_token_usage_history_action'), table_name='token_usage_history')
    op.drop_table('token_usage_history')
    op.drop_index(op.f('ix_shared_tokens_vendor'), table_name='shared_tokens')
    op.drop_index(op.f('ix_shared_tokens_user_id'), table_name='shared_tokens')
    op.drop_index(op.f('ix_shared_tokens_status'), table_name='shared_tokens')
    op.drop_index('idx_user_vendor_unique', table_name='shared_tokens')
    op.drop_table('shared_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
