stages:
  - build

variables:
  IMAGE_NAME: hub.upyun.com/holdcloud/sharinmod

build-and-push-backend:
  stage: build
  before_script:
    - docker login -u ${HUB_UPYUN_USER} -p ${HUB_UPYUN_PASSWORD} hub.upyun.com
  script:
    - docker build --build-arg target=runtime -t $IMAGE_NAME-backend:$CI_COMMIT_TAG .
    - docker push $IMAGE_NAME-backend:$CI_COMMIT_TAG
  only:
    - tags
  tags:
    - on-line-docker-builder

build-and-push-frontend:
  stage: build
  before_script:
    - docker login -u ${HUB_UPYUN_USER} -p ${HUB_UPYUN_PASSWORD} hub.upyun.com
  script:
    - docker build --build-arg target=runtime -t $IMAGE_NAME-frontend:$CI_COMMIT_TAG .
    - docker push $IMAGE_NAME-frontend:$CI_COMMIT_TAG
  only:
    - tags
  tags:
    - on-line-docker-builder
