services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    networks:
      - my-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    networks:
      - my-network
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@db:5432/sharinmod
      - REDIS_DATABASE=redis://redis:6379/0
      - LITELLM_WEBHOOK_IP_WHITELIST_STR=192.168.96.7
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app

  # Consumer for LiteLLM callback processing
  litellm-callback-consumer:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
      - backend
    networks:
      - my-network
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@db:5432/sharinmod
      - REDIS_DATABASE=redis://redis:6379/0
    restart: unless-stopped
    command: ["python", "-m", "api.consumers.litellm_callback_consumer"]
    volumes:
      - ./backend:/app

  db:
    image: postgres:15-alpine
    restart: always
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sharinmod

  redis:
    image: redis:7-alpine
    restart: always
    container_name: redis
    networks:
      - my-network

  nginx:
    image: nginx:alpine
    ports:
      - "18888:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - my-network

volumes:
  postgres_data:

networks:
  my-network:
    driver: bridge

