litellm_settings:
  num_retries: 6
  request_timeout: 600
  telemetry: False
  success_callback: ["generic_api"]
  failure_callback: ["generic_api"]
  callbacks:
    - custom_callbacks.key_alias_model_router   # 注册自定义回调

router_settings:
  routing_strategy: usage-based-routing-v2
  redis_host: "redis"
  redis_password: ""
  redis_port: "6379"
  enable_pre_call_checks: false

general_settings:
  database_connection_pool_limit: 10
  maximum_spend_logs_retention_period: "1d"
  maximum_spend_logs_retention_interval: "1h"

literals:
  turn_off_message_logging: false
