events {
    worker_connections 1024;
}

http {
    upstream frontend {
        server frontend:3000;
    }

    upstream backend {
        server backend:8000;
    }

    server {
        listen 80;
        client_max_body_size 50M;

        location /api/openai/ {
            proxy_pass http://10.0.5.176:4000/;
        }

        location /api/anthropic/ {
            proxy_pass http://10.0.5.176:4000/;
        }

        location /api/ {
            proxy_pass http://backend;
        }

        location / {
            proxy_pass http://frontend;
        }
    }
}